version: '3.1'
services:
  db:
    image: mysql
    container_name: anime
    environment:
      MYSQL_DATABASE: 'anime'
      MYSQL_ROOT_PASSWORD: 1234
    ports:
      - "3306:3306"

volumes:
  develop_data: